// Code generated by "stringer -type=MessageType"; DO NOT EDIT.

package message

import "strconv"

const _MessageType_name = "CONNECTCONNACKPUBLISHPUBACKPUBRECPUBRELPUBCOMPSUBSCRIBESUBACKUNSUBSCRIBEUNSUBACKPINGREQPINGRESPDISCONNECTAUTH"

var _MessageType_index = [...]uint8{0, 7, 14, 21, 27, 33, 39, 46, 55, 61, 72, 80, 87, 95, 105, 109}

func (i MessageType) String() string {
	i -= 1
	if i >= MessageType(len(_MessageType_index)-1) {
		return "MessageType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
